name: Build and Push Docker Image to ECR

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
        IMAGE_TAG: ${{ secrets.IMAGE_TAG }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Send Success Notification to Slack
      if: success()
      run: |
        # Your code to send a success notification to Slack
        message="Image successfully uploaded and scanned."
        channel="#your-channel-name"
        python send_slack_notification.py "$message" "$channel"

    - name: Send Failure Notification to Slack
      if: failure()
      run: |
        # Your code to send a failure notification to Slack
        message="Image upload or scan failed. Check the pipeline logs for details."
        channel="#your-channel-name"
        python send_slack_notification.py "$message" "$channel"

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.docker
        key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile') }}
        restore-keys: |
          ${{ runner.os }}-docker-
